name: Build project and save artifact

on:
  push:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 21
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build with Gradle
        run: ./gradlew core:build
      
      - name: Upload Latest Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: core/build/libs/*.jar  # This will match all .jar files; the latest one is typically the one created last
          # Optionally, you can use 'core/build/libs/your-artifact-name-*.jar' 
          # to specify a pattern if you have a versioning scheme in place.
